# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('unterschrift', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kapitel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kapitelname', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='artikel',
            name='kapitel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lernen.Kapitel'),
        ),
    ]
