# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='artikel',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
