# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernen', '0003_artikelimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikelimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article/'),
        ),
        migrations.AlterField(
            model_name='artikelimages',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
