# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernen', '0005_auto_20180625_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='unterschrift',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
