# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernen', '0006_auto_20180625_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
