# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernen', '0007_auto_20180625_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
