# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lernen', '0008_artikel_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='unten',
            field=models.BooleanField(default=False),
        ),
    ]
