# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 19:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lernen', '0009_artikel_unten'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
