# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image_name', models.CharField(max_length=30)),
                ('auswahllocation', models.TextField()),
            ],
        ),
    ]
