# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubung', '0002_auto_20180617_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='question',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
