# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubung', '0003_auto_20180617_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='coordinates',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
