# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubung', '0006_auto_20180627_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='frage',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
